<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2023-09-17T19:58:44.947647100Z</date>
  <millis>1694980724947</millis>
  <nanos>647100</nanos>
  <sequence>0</sequence>
  <logger>main.UsersController</logger>
  <level>SEVERE</level>
  <class>main.UsersController</class>
  <method>getUsers</method>
  <thread>19</thread>
  <message>java.net.ConnectException: Connection refused: connect</message>
</record>
<record>
  <date>2023-09-17T19:58:45.267856Z</date>
  <millis>1694980725267</millis>
  <nanos>856000</nanos>
  <sequence>1</sequence>
  <logger>main.UsersController</logger>
  <level>SEVERE</level>
  <class>main.UsersController</class>
  <method>getUsers</method>
  <thread>19</thread>
  <message>java.net.ConnectException: Connection refused: connect</message>
</record>
<record>
  <date>2023-09-17T19:58:45.267856Z</date>
  <millis>1694980725267</millis>
  <nanos>856000</nanos>
  <sequence>1</sequence>
  <logger>main.UsersController</logger>
  <level>SEVERE</level>
  <class>main.UsersController</class>
  <method>getUsers</method>
  <thread>19</thread>
  <message>java.net.ConnectException: Connection refused: connect</message>
</record>
